name: Selenium Headless Job

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos (mínimo permitido pelo GitHub Actions)
  workflow_dispatch:       # Permite disparar manualmente também

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        echo 'CHROME_BIN=/usr/bin/chromium-browser' >> $GITHUB_ENV

    - name: Run Selenium script
      env:
        CHROME_BIN: /usr/bin/chromium-browser
      run: |
        python main.py
