name: Selenium Automation

on:
  schedule:
    - cron: '*/5 * * * *'  # a cada 5 minutos
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar Python e dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar automação Selenium
        run: python automacao.py
